services:
  app:
    image: 'listmonk/listmonk:latest'
    container_name: listmonk_app
    restart: unless-stopped
    ports:
      - '9000:9000'
    networks:
      - listmonk
    hostname: listmonk.example.com
    command:
      - sh
      - '-c'
      - "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''"
    environment:
      LISTMONK_app__address: '0.0.0.0:9000'

      LISTMONK_db__user: '${LISTMONK_DB_USER:-}'
      LISTMONK_db__password: '${LISTMONK_DB_PASSWORD:-}'
      LISTMONK_db__database: '${LISTMONK_DB_DATABASE:-}'
      LISTMONK_db__host: '${LISTMONK_DB_HOST:-}'
      LISTMONK_db__port: 25060
      LISTMONK_db__ssl_mode: require

      LISTMONK_db__max_open: 25
      LISTMONK_db__max_idle: 25
      LISTMONK_db__max_lifetime: 300s
      TZ: Etc/UTC
      LISTMONK_ADMIN_USER: '${LISTMONK_ADMIN_USER:-}'
      LISTMONK_ADMIN_PASSWORD: '${LISTMONK_ADMIN_PASSWORD:-}'
    volumes:
      - './uploads:/listmonk/uploads:rw'

networks:
  listmonk: {}

